services:

  web1:
    image: nginx:latest
    container_name: web1

    ports:
      - "8081:80"

    volumes:
      - ./web1:/usr/share/nginx/html

    networks:
      - mynetwork


  web2:
    image: nginx:latest
    container_name: web2

    ports:
      - "8082:80"

    volumes:
      - ./web2:/usr/share/nginx/html

    networks:
      - mynetwork


networks:
  mynetwork:
